### ISSUE TITLE
1003 피보나치 함수

### ISSUE THREAD

**Issue by jeongyoung-kim** [moonps/ProblemSolving#1]
https://www.acmicpc.net/problem/1003

>문제를 풀면 commit 링크와 함께 댓글 작성한 후 체크해주세요.
- [x] 정영
- [x] 은경

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/887e777dadcd1afac5ac4a1536843439949679f8
코드 추가했습니다~

**Comment by gungadinn** [comment]
고생하셨습니다~

**Comment by gungadinn** [comment]
https://github.com/moonps/ProblemSolving/commit/357dbcb15b398775be5aeb9a3c198d978e6409a7
문제 풀었습니다!
