### ISSUE TITLE
완전탐색에 익숙해지려고 만든 이슈

### ISSUE THREAD

**Issue by gungadinn** [moonps/ProblemSolving#11]
연산자 끼워넣기를 풀려고 했는데 어떻게 풀어야할지 감이 안 와서 잠시 다른 문제들 먼저 풀어봅니다 (ᵕ̣̣̣̣̣̣﹏ᵕ̣̣̣̣̣̣)
~알고리즘 분류는 일부러 안 넣었고~ 기존에 올라온 문제들이랑 비슷한 것들 계속해서 댓글로 추가할게요!

> 문제를 풀면 commit 링크와 함께 댓글 작성한 후 체크해주세요.

* 일곱 난쟁이 https://acmicpc.net/problem/2309
- [x] 정영
- [x] 은경
<br>

* 부분 수열의 합 https://www.acmicpc.net/problem/1182
- [x] 정영
- [x] 은경
<br>

* 연구소2 https://www.acmicpc.net/problem/17141
- [x] 정영
- [x] 은경
<br>

* 모든 순열 https://www.acmicpc.net/problem/10974
- [x] 정영
- [x] 은경
<br>

* 차이를 최대로 https://www.acmicpc.net/problem/10819
- [x] 정영
- [x] 은경
<br>

* 원판원 순회 https://www.acmicpc.net/problem/10971
- [x] 정영
- [x] 은경
<br>

* 암호 만들기 https://www.acmicpc.net/problem/1759
- [x] 정영
- [x] 은경

**Comment by gungadinn** [comment]
65a85d78848ac387a10c97cc40d332991b3646a1
<br>

일곱 난쟁이 풀었습니다. 답이 여러개일때 출력 한번만 처리하는거에서 조금 헤맴ㅠㅠ

**Comment by gungadinn** [comment]
beaf6f0fe7baefb349d020ed40178b326abd3260

조건 못 찾아서 헤매고 있던거 갓주찬님이 도와주셨습니다.. 갓갓
그나저나 맨날 헤매네여 ㅎ;

**Comment by gungadinn** [comment]
db93c5d0ad2ed459de183c16f288df8168197496

아무리 생각해도 승원이 너무 못됐네요. 바이러스 왜 유출하냐 쒸익쒸익

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/68c67eed9ab7dd52fe8c0de2c8ee87b80e01ae13
일곱난쟁이요~ 1년전 푼 코드가 있던데 신기하네...
새로 풀었습니다.

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/aeefa497e8bcc5edec8dc18c9d3f2b1fa92dd01b
부분수열의합
저도 헤매다 찾아냈습니다. ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 하..

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/cf30c0d9af7a4a3e6dde785767f776663df0851f
연구소2
오랜만에 코드가 길군요
나쁜짓도 정성스럽게~

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/8930b25e6543ab01c4d866478ce962e871f2366a
모든 순열 풀어습니다

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/47b16167d76f828afeb9fc14d21b01204df45a2f
차이를 최대로

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/1b5ae3e09ae3fd2ba3693ff6c507058919ef0107
외판원순회2
요건 조오금 다르네요

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/af0676466bf464c8a5bba4d2afd387c8b6645100
암호 만들기
비슷한 문제들이 많군요
모음에 뭐뭐 있는지... 불안해서 인터넷찬스 한번 썼습니다.

**Comment by gungadinn** [comment]
cb34722dacfb647ee2dbe29bbd816dad238cbd98

 암호만들기 추가합니다~
저도 모음에 뭐뭐 있는지 가물가물해서 인터넷 찬스 썼어요 호호

**Comment by gungadinn** [comment]
43b3ed6e19cfc30914646066fb55d15d73c067f0

히히.. 늦어서 죄송합니다 ༼༎ຶ෴༎ຶ༽

**Comment by gungadinn** [comment]
82776a80af5c1f5917e0c6ca31fa7366dab7ab1d

늦어서 죄송합니다....

**Comment by gungadinn** [comment]
fe8667e689d21e0b3450b4b42376ffc000e13261

외판원 순회2!!!
드디어 닫습니다~~
