### ISSUE TITLE
Academy_특이한자석

### ISSUE THREAD

**Issue by jeongyoung-kim** [moonps/ProblemSolving#13]
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWIeV9sKkcoDFAVH
> 문제를 풀면 commit 링크와 함께 댓글 작성한 후 체크해주세요.
- [x] 정영
- [x] 은경

요것도 구현문제인듯 합니다.

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/021c360194add13e34e1d49cdb9394b99c2c7812
코드 추가~

**Comment by gungadinn** [comment]
85b6ffb76e6b01a362ddaaf3b9742fd857e4c653
닫습니다ㅏㅏㅏㅏ
check_arr 함수 부분 무식하게 첫 시작이 1,2,3,4 일 때 다 나눠서 했는데 오빠 코드 보니까 훨씬 깔끔하길래..ㅎㅎ
오빠꺼 보고 고쳤어용
