### ISSUE TITLE
9328_열쇠

### ISSUE THREAD

**Issue by jeongyoung-kim** [moonps/ProblemSolving#2]
https://www.acmicpc.net/problem/9328

>문제를 풀면 commit 링크와 함께 댓글 작성한 후 체크해주세요.
- [x] 정영
- [x] 은경

상근이는 도둑놈~

**Comment by jeongyoung-kim** [comment]
문제 이거 뭐죠? 왜 계속 틀리죠 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 하

**Comment by gungadinn** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 저 열심히 푸는 중입니다ㅠㅠ 쪼매만 기다려주세여...

**Comment by jeongyoung-kim** [comment]
깨름찍 하지만... 풀었습니다...
https://github.com/moonps/ProblemSolving/commit/60adff16879d8d80383bbc88e0aa918c59387dc7

**Comment by gungadinn** [comment]
https://github.com/moonps/ProblemSolving/commit/742eb3e212c9157abe1fb6180e78ad2a773a8e4b

드디어....ㅠㅠㅠㅠㅠㅠㅠ
