### ISSUE TITLE
6603 로또

### ISSUE THREAD

**Issue by jeongyoung-kim** [moonps/ProblemSolving#4]
https://www.acmicpc.net/problem/6603

> 문제를 풀면 commit 링크와 함께 댓글 작성한 후 체크해주세요.

- [x] 정영
- [x] 은경

로또는 믿음입니다. 매주 5천원이면 행복을 살수 있읍니다!

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/bd01b297bccdc9bde6de8dd17196739e4efc0792
제출 했습니다~

**Comment by gungadinn** [comment]
480ac4f77cb23d90ce3fb734695d6a468c036f01

어렵.....ㅠㅠㅠㅠㅠㅠㅠㅠㅠ
