### ISSUE TITLE
14502_연구소

### ISSUE THREAD

**Issue by gungadinn** [moonps/ProblemSolving#5]
https://www.acmicpc.net/problem/14502
> 문제를 풀면 commit 링크와 함께 댓글 작성한 후 체크해주세요.
- [x] 정영
- [x] 은경

바이러스를 막읍시다!

**Comment by jeongyoung-kim** [comment]
오! 이거 기출 아닙니까? 나 인턴 필기셤때 나왔던..... 못풀었었던...ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by gungadinn** [comment]
@jeongyoung-kim 와 댓글 달려서 오빠 벌써 푼 줄 알고 놀랬어욬ㅋㅋㅋㅋㅋ 기출인지도 몰랐는데 어떨결에 얻어걸렸네요... 껄껄

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/bb9945a20979cb43349a219808041b0743393850
풀었습니다~~
뭔가 삼성 스타일 문제가 있는건가? 익숙한 듯한...

**Comment by gungadinn** [comment]
aaa671618247c6a99f18e49ae79ec940f0ad70e9

드디어! 풀었습니다!!!

**Comment by gungadinn** [comment]
19cb14eb918c8274f9f458023dce9a6c85f11c59
복습하는 겸 다시 풀어보았읍니다
