### ISSUE TITLE
14888_연산자 끼워넣기

### ISSUE THREAD

**Issue by jeongyoung-kim** [moonps/ProblemSolving#6]
https://www.acmicpc.net/problem/14888
> 문제를 풀면 commit 링크와 함께 댓글 작성한 후 체크해주세요.
- [x] 정영
- [x] 은경

삼성 기출 문제집에서 가져왔습니다~
( https://www.acmicpc.net/workbook/view/1152 )

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/8d4f16e2328891761a621652b25e2eaba14707e5
제출 합니다!

**Comment by gungadinn** [comment]
3f505e8eb22a37349fed54c768a0aa557d5aa65a
끗
