### ISSUE TITLE
2606_바이러스

### ISSUE THREAD

**Issue by gungadinn** [moonps/ProblemSolving#7]
https://www.acmicpc.net/problem/2606

> 문제를 풀면 commit 링크와 함께 댓글 작성한 후 체크해주세요.

- [x]  정영
- [x]   은경

기출 풀기 전에 머리 깨우는 용으로 풀어봤습니다
심심 할 때 푸세여 ㅎ_ㅎ

**Comment by gungadinn** [comment]
f3ab6607ce7791f7329639c5caefe315781c75b8 은경 코드

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/915a9f40c66c1a1cf2c78eb87f134201b6401ed4
제출!
