### ISSUE TITLE
1012_유기농배추 / 1697_숨바꼭질

### ISSUE THREAD

**Issue by gungadinn** [moonps/ProblemSolving#8]
https://www.acmicpc.net/problem/1012

문제를 풀면 commit 링크와 함께 댓글 작성한 후 체크해주세요.

- [x]  정영
- [x]  은경
---
https://www.acmicpc.net/problem/1697

문제를 풀면 commit 링크와 함께 댓글 작성한 후 체크해주세요.

- [x]  정영
- [x]  은경

**Comment by gungadinn** [comment]
a159579c4b4860cee12934eca5ec33f3f176eee4
멍청한 김은경은... 오늘도 기출 푸는데 실패했습니다... 오늘은 이걸로 대체하고 내일 마저 도전해볼게욥 ㅠ_ㅠ

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/b56b5878e2a5a678759122a577df240d216c4c37
유기농배추 코드 추가!

**Comment by jeongyoung-kim** [comment]
챤챤히 하시쥬~

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/cde7e51e5c3b3090ed85677eb93dac814700703b
숨바꼭질 코드 추가요~

**Comment by jeongyoung-kim** [comment]
이슈 닫습니당
