### ISSUE TITLE
15649_N과 M (1)

### ISSUE THREAD

**Issue by jeongyoung-kim** [moonps/ProblemSolving#9]
https://www.acmicpc.net/problem/15649
> 문제를 풀면 commit 링크와 함께 댓글 작성한 후 체크해주세요.
- [x] 정영
- [x] 은경

이문제 맞나요? ㅎㅎ

**Comment by jeongyoung-kim** [comment]
https://github.com/moonps/ProblemSolving/commit/524e91fc7e33ac5a24d832edfa330b2d3969d253
요건 순열 인가요? 연산자끼워넣기랑 똑같은거 같습니다.
로또는 조합이라 조금 다른 느낌 아닌가 싶습니다.

**Comment by gungadinn** [comment]
22e99ce98e1855c6990312f553dc45c83692e26c

어쩐지 아무리 폴더 만들어도 안 올려지길래 봤더니 이미 올려놓으셨네요ㅎㅎㅋㅋㅋㅋ
연산자 끼워놓기를 아직 안 봐서 잘 모르겠지만 읽어보도록 하겠습니당..
근데 로또랑 똑같이 거꾸로 가는건 맞지 않나여?

**Comment by gungadinn** [comment]
![15649](https://user-images.githubusercontent.com/49109738/61808597-ae96c080-ae76-11e9-81d6-f2328e65f8e6.jpeg)

아 뭐야 이미지 업로드 안 하고 그냥 드래그 해도 되네요..ㅎ
근데 로또나 N과M(1)이나 꼬리 물고(?) 푸는건 같지 않나용?

**Comment by gungadinn** [comment]
아 이해간다
이 문제는 n개 중 m개 뽑는건데 순서가 있으니까 순열인거고
로또는 n개 중에서 순서 상관없이 m개 뽑는데 경우의 수를 출력만 오름차순으로 해준건가요..?

**Comment by jeongyoung-kim** [comment]
음 탐색 하는 순서(1.작은수를 먼저뽑으면 오름차순 2.큰수를 먼저 뽑으면 내림차순)는 사실 상관없는것 같고(문제에서 오름차순을 원하니 1번으로 하면될듯?)
재귀호출 할때
1. 순열의 경우는 뽑았던 것도 순서가 다르면 다시 뽑을수있도록 해줘야 하고
2. 조합은 뽑았던 거면 다시 뽑지 않도록 해주는
차이가 있는듯 합니다

말로 설명이 힘드네 ㅋㅋㅋㅋㅋㅋㅋㅋ
서로 코드보고 어찌 돌아가는지 파악 하면 도움 될듯!

**Comment by jeongyoung-kim** [comment]
꼬리물고 푼다는건 뭔말인가 잘 모르겟소이다 ㅋㅋㅋㅋㅋㅋㅋ 음성대화로 이해합시다 ㅋㅋㅋㅋㅋ 어쨋든 순열이든 조합이든 전체적인 탐색 아이디어는 같아도 될것 같슴다

**Comment by jeongyoung-kim** [comment]
아 머야 코드 똑같네 ㅋㅋㅋㅋ
로또도 비슷한 아이디어로 가능 합니다
이 문제 코드에서 dfs 함수 안에 재귀호출 하는 for문만 잘 바꿔주면... 전 매개변수를 하나더 썼습니다
